version: '2'
services:
  mongodb:
    image: mongo:3.4.24-xenial
    volumes:
      - ./storage/mongodb:/data/db:z
  redis:
    image: redis:alpine
    volumes:
      - ./storage/redis:/data:z
  hpfeeds:
    image: stingar/hpfeeds:1.8
    links:
      - mongodb:mongodb
    ports:
      - "10000:10000"
  mnemosyne:
    image: stingar/mnemosyne:1.8
    links:
      - mongodb:mongodb
      - hpfeeds:hpfeeds
  chnserver:
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - ./config/collector:/etc/collector:z
      - ./storage/chnserver/sqlite:/opt/sqlite:z
      - ./certs:/tls:z
    links:
      - mongodb:mongodb
      - redis:redis
      - hpfeeds3:hpfeeds3
    ports:
      - "80:80"
      - "443:443"
